### ISSUE TITLE
SANS MGT433 or LDR433 

### ISSUE THREAD

**Issue by Vuccappella** [MrM8BRH/SuperLibrary#2]
Any chance to share materials for SANS MGT433 or LDR433 (new name) ?

**Comment by MrM8BRH** [comment]
Hi Vuccappella,

I don't have the course you mentioned. When I get it, I'll upload it to the library.

However, I have added new courses to the library.

![image](https://github.com/MrM8BRH/SuperLibrary/assets/34133187/592fba3e-5b74-416d-a438-011ba022c552)
